
experiment_name: "gigar4sft_trxgeo"

embedding_path: "/home/maorlov/mbd_paper/data/embeddings/llm/gigar4sft_trxgeo.parquet"
target_path: "/home/maorlov/mbd_paper/data/mbd_targets_balanced.parquet"

log_dir: "/home/maorlov/mbd_paper/logs/"

results_dir: "/home/maorlov/mbd_paper/results/llm/"


apply_pca: true

automl_settings:
  n_threads: 8
  n_folds: 5
  test_size: 0.2
  timeout: 120
